APPS = timeadd xmail xjoin xgroup xcut xping socks

checkflow_files = checkflow.o
checkflow_flags = -lutil -lcomBasic

timeadd_files = timeadd.o
xmail_files = sendmail.o
xmail_flags = -lcomBasic
xjoin_files = xjoin.o
xcut_files = xcut.o
xgroup_files = xgroup.o
xgroup_flags = -lcomBasic
xping_files = xping.o
socks_files = socks.o
socks_flags = -lcomBasic

LDFLAGS = -lutil

include ../Makefile.all
